# For more information: https://laravel.com/docs/sail
version: '3'
services:
    frontend:
        stdin_open:
            true
        build:
            context: .
            dockerfile: Dockerfile
        image: nuxtjs14/app
        ports:
            - '${SITE_PORT:-3000}:3000'
        volumes:
            - '.:/usr/src/nuxt-app'
        networks:
            - nuxtjsnet
networks:
    nuxtjsnet:
        driver: bridge